# event:
#    path:     /
#    defaults: { _controller: "EventBundle:Event:index" }

event_show:
    path:     /{id}/show
    defaults: { _controller: "EventBundle:Event:show" }

event_new:
    path:     /new
    defaults: { _controller: "EventBundle:Event:new" }

event_create:
    path:     /create
    defaults: { _controller: "EventBundle:Event:create" }
    methods:  POST

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }

event_update:
    path:     /{id}/update
    defaults: { _controller: "EventBundle:Event:update" }
    methods:  [POST, PUT]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    methods:  [POST, DELETE]
